-- Per-event analytics log for drill-down statistics in the admin panel.
-- Additive only: new table, no changes to existing data. Safe to re-run.
-- Never stores phone numbers, IP addresses or raw User-Agent strings.
CREATE TABLE IF NOT EXISTS public.analytics_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz NOT NULL DEFAULT now(),
  event_type text NOT NULL,
  location_id text,
  user_id text,
  user_role text,
  session_id text,
  path text,
  referrer_host text,
  utm_source text,
  utm_medium text,
  utm_campaign text,
  device_type text,
  os text,
  browser text,
  meta jsonb NOT NULL DEFAULT '{}'::jsonb,
  legacy boolean NOT NULL DEFAULT false
);

CREATE INDEX IF NOT EXISTS analytics_events_created_idx
  ON public.analytics_events (created_at DESC);
CREATE INDEX IF NOT EXISTS analytics_events_type_created_idx
  ON public.analytics_events (event_type, created_at DESC);
CREATE INDEX IF NOT EXISTS analytics_events_location_created_idx
  ON public.analytics_events (location_id, created_at DESC)
  WHERE location_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS analytics_events_session_idx
  ON public.analytics_events (session_id)
  WHERE session_id IS NOT NULL;

ALTER TABLE public.analytics_events ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "analytics_events_service_all" ON public.analytics_events;
CREATE POLICY "analytics_events_service_all"
  ON public.analytics_events FOR ALL
  TO service_role
  USING (true)
  WITH CHECK (true);

REVOKE ALL ON public.analytics_events FROM anon, authenticated;

COMMENT ON TABLE public.analytics_events IS
  'Mapfix per-event analytics (admin drill-down). Written by API service_role only.';

-- One-time backfill of history we already have (marked legacy = true).
-- Card clicks: only aggregate counters exist; time = last click of that counter
-- (exact when the counter is 1).
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM public.analytics_events WHERE legacy) THEN
    INSERT INTO public.analytics_events (created_at, event_type, location_id, legacy, meta)
    SELECT c.updated_at,
           substring(c.click_key FROM '^loc:([a-z_]+):'),
           substring(c.click_key FROM '^loc:[a-z_]+:(.+)$'),
           true,
           jsonb_build_object('backfill', 'catalog_clicks', 'counter', c.clicks)
    FROM public.catalog_clicks c
    CROSS JOIN LATERAL generate_series(1, GREATEST(c.clicks, 0)) g
    WHERE c.click_key ~ '^loc:[a-z_]+:.+$';

    -- Donate / Pro clicks (billing log has exact time and user)
    INSERT INTO public.analytics_events (created_at, event_type, user_id, user_role, legacy, meta)
    SELECT (e->>'at')::timestamptz,
           CASE WHEN e->>'type' = 'subscribe' THEN 'subscribe' ELSE 'donate' END,
           NULLIF(e->>'userId', ''),
           NULLIF(e->>'role', ''),
           true,
           jsonb_build_object('backfill', 'billing')
    FROM public.catalog_snapshots s
    CROSS JOIN LATERAL jsonb_array_elements(
      CASE WHEN jsonb_typeof(s.master_catalog->'events') = 'array'
           THEN s.master_catalog->'events' ELSE '[]'::jsonb END) e
    WHERE s.id = 'billing' AND e->>'at' IS NOT NULL;

    -- Recent searches kept in product analytics
    INSERT INTO public.analytics_events (created_at, event_type, session_id, legacy, meta)
    SELECT (e->>'at')::timestamptz,
           'search',
           NULLIF(e->>'sid', ''),
           true,
           jsonb_build_object('q', left(e->>'q', 120), 'source', e->>'source',
                              'matched', COALESCE((e->>'matched')::boolean, false),
                              'backfill', 'recentSearches')
    FROM public.catalog_snapshots s
    CROSS JOIN LATERAL jsonb_array_elements(
      CASE WHEN jsonb_typeof(s.master_catalog->'recentSearches') = 'array'
           THEN s.master_catalog->'recentSearches' ELSE '[]'::jsonb END) e
    WHERE s.id = 'product_analytics' AND e->>'at' IS NOT NULL;

    -- Registrations with a known join date (users.created_at, migration 017)
    IF EXISTS (SELECT 1 FROM information_schema.columns
               WHERE table_schema = 'public' AND table_name = 'users' AND column_name = 'created_at') THEN
      EXECUTE $q$
        INSERT INTO public.analytics_events (created_at, event_type, user_id, user_role, legacy, meta)
        SELECT u.created_at, 'register', u.id::text, u.role, true,
               jsonb_build_object('backfill', 'users.created_at')
        FROM public.users u
        WHERE u.created_at IS NOT NULL
      $q$;
    END IF;
  END IF;
END $$;
